---

- include: ubuntu.yml
  when: ansible_os_family == 'Debian'
  tags: mariadb-deploy

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: mariadb-deploy

- include: configure.yml
  tags: mariadb-configure
