---

- include: ubuntu.yml
  when: ansible_os_family == 'Debian'
  tags: cloudera-scm-server-install

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: cloudera-scm-server-install

- include: config_scm.yml
  tags: cloudera-scm-config-scm
