---
# Install Cloudera's Service and Configuration Manager (SCM) on Ubuntu system

- name: Import Cloudera APT key
  become: yes
  apt_key: url="https://archive.cloudera.com/cdh{{ cloudera_manager_version|regex_replace('^([0-9]+)(.*)$', '\1') }}/{{ ansible_distribution|lower }}/{{ ansible_distribution_release }}/amd64/cdh/archive.key" state=present
  when: cloudera_manager_version is defined

- name: Import Cloudera APT key
  become: yes
  apt_key: url="https://archive.cloudera.com/cdh5/{{ ansible_distribution|lower }}/{{ ansible_distribution_release }}/amd64/cdh/archive.key" state=present
  when: cloudera_manager_version is not defined

- name: Set up APT Cloudera repo
  become: yes
  template: src=cloudera_manager.list.j2 dest=/etc/apt/sources.list.d/cloudera_manager.list
  tags: cdh-scm-base, cdh-scm-repo

- name: Check Java
  command: which java
  register: java_check
  ignore_errors: yes
  tags: cdh-agent-jdk, cdh-agent-base

- name: Show Java test
  debug: var=java_check
  tags: cdh-agent-jdk, cdh-agent-base

- block:
    - name: Add webupd8team APT Repository for Oracle Java
      become: yes
      apt_repository: repo='ppa:webupd8team/java'

    - name: Update APT cache
      become: yes
      apt: update_cache=yes

    - name: "Accept Oracle Java {{ cloudera_java_family }} License"
      become: yes
      debconf: name='oracle-java{{ cloudera_java_family }}-installer' question='shared/accepted-oracle-license-v1-1' value='yes' vtype='select'

    - name: "Install Oracle Java {{ cloudera_java_family }}"
      become: yes
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - "oracle-java{{ cloudera_java_family }}-installer"
        - "oracle-java{{ cloudera_java_family }}-set-default"

  rescue:
    - name: "Remove failed Oracle Java {{ cloudera_java_family }} "
      become: yes
      apt: name={{item}} state=absent
      with_items:
        - "oracle-java{{ cloudera_java_family }}-installer"
        - "oracle-java{{ cloudera_java_family }}-set-default"
      ignore_errors: yes

    - name: Remove webupd8team APT Repository
      become: yes
      shell: "rm -f /etc/apt/sources.list.d/*webupd8team_java*.list"

    - name: Clean APT
      become: yes
      shell: apt-get -f install -y && apt-get autoremove -y &&  apt-get clean -y

    - name: Update APT
      become: yes
      apt: update_cache=yes

    - name: "Install OpenJDK {{ cloudera_java_family }}"
      become: yes
      apt: name={{ item }} state=present
      with_items:
        - "openjdk-{{ cloudera_java_family }}-jdk"
  when: "'failed' in java_check"
  tags: cdh-agent-jdk, cdh-agent-base

- name: Search Java path
  shell: readlink -f `which java`
  register: java_path
  tags: cdh-agent-jdk, cdh-agent-base, cdh-java-unlimited

- name: Copy UnlimitedJCEPolicy
  become: yes
  copy: src={{ item }} dest="{{ java_path.stdout|dirname }}/../lib/security/"
  with_items:
    - local_policy.jar
    - US_export_policy.jar
  tags: cdh-agent-jdk, cdh-agent-base, cdh-java-unlimited

- name: Add MySQL JDBC connector
  become: yes
  copy: src=mysql-connector-java-5.1.40-bin.jar dest=/usr/share/java/mysql-connector-java.jar
  tags: cdh-agent-jdk, cdh-agent-base, cdh-agent-jdbc

- name: Create cloudera-scm user
  become: yes
  user: name=cloudera-scm state=present home=/opt/cloudera shell=/bin/bash
  tags: cdh-scm-base

- name: Install Cloudera Manager server
  become: yes
  apt: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
    - cloudera-manager-daemons
    - cloudera-manager-server
  tags: cdh-scm-base

- name: Update Cloudera SCM Manager default operation
  become: yes
  template: src=default_cloudera-scm-server.j2 dest=/etc/default/cloudera-scm-server
  tags: cdh-scm-base

- name: Update Cloudera Manager DB configuration
  become: yes
  template: src=db.properties.j2 dest=/etc/cloudera-scm-server/db.properties
  when: cloudera_external_database is defined
  tags: cdh-scm-manager-config

- name: Install Embedded Cloudera Mananager Database
  become: yes
  apt: name=cloudera-manager-server-db-2 state=present allow_unauthenticated=yes
  when: cloudera_external_database is not defined

- name: Start Embedded Cloudera Manager Database
  become: yes
  service: name=cloudera-scm-server-db state=started
  when: cloudera_external_database is not defined

- name: Pause 30'
  pause: seconds=30

- name: Start Cloudera Manager
  become: yes
  service: name=cloudera-scm-server state=started
  tags: cdh-scm-manager-config

- name: Check Cloudera Manager port
  wait_for: port=7180 delay=15 timeout=120
  tags: cdh-scm-manager-config
