---
- name: "Enable IP forward 1"
  shell: "sysctl net.ipv4.ip_forward=1"

- name: "Enable IP forward 2"
  lineinfile:
    line: "net.ipv4.ip_forward=1"
    dest: "/etc/sysctl.conf"
    state: "present"

- name: Add rules to iptables
  iptables: table=nat chain=POSTROUTING jump=MASQUERADE comment="OpenVPN config - Ansible Managed" state=present

- name: Install iptables-persistent
  apt: name=iptables-persistent state=present

- name: Save iptables
  shell: service iptables-persistent save
  when: "{{ ansible_distribution_version | version_compare('16.04', '<') }}"

- name: Save iptables
  shell: sudo netfilter-persistent save 
  when: "{{ ansible_distribution_version | version_compare('16.04', '>=') }}"
