---
# Install Cloudera's Service and Configuration Manager (SCM) on RedHat system

- name: Set up YUM Cloudera repo
  become: yes
  template: src=cloudera_manager.repo.j2 dest=/etc/yum.repos.d/cloudera_manager.repo
  tags: cdh-scm-base, cdh-scm-repo

- name: Install necessary packages
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - wget
    - psmisc
  tags: cdh-scm-base

- name: Check Java
  command: which java
  register: java_check
  ignore_errors: yes
  tags: cdh-agent-jdk, cdh-agent-base

- name: Show Java test
  debug: var=java_check
  tags: cdh-agent-jdk, cdh-agent-base

- name: Install java
  become: yes
  yum: name="java-1.{{ cloudera_java_family }}.0-openjdk"
  when: "'failed' in java_check"
  tags: cdh-agent-jdk, cdh-agent-base

- name: Search Java path
  shell: readlink -f `which java`
  register: java_path
  tags: cdh-agent-jdk, cdh-agent-base, cdh-java-unlimited

- name: Copy UnlimitedJCEPolicy
  become: yes
  copy: src={{ item }} dest="{{ java_path.stdout|dirname }}/../lib/security/"
  with_items:
    - local_policy.jar
    - US_export_policy.jar
  tags: cdh-agent-jdk, cdh-agent-base, cdh-java-unlimited

- name: Add MySQL JDBC connector
  become: yes
  copy: src=mysql-connector-java-5.1.40-bin.jar dest=/usr/share/java/mysql-connector-java.jar
  tags: cdh-agent-jdk, cdh-agent-base, cdh-agent-jdbc

- name: Create cloudera-scm user
  become: yes
  user: name=cloudera-scm state=present home=/opt/cloudera shell=/bin/bash
  tags: cdh-scm-base

- name: Install Cloudera Manager server
  become: yes
  yum: name={{ item }} state=present disable_gpg_check=yes
  with_items:
    - cloudera-manager-daemons
    - cloudera-manager-server
  tags: cdh-scm-base

- name: Update Cloudera SCM Manager default operation
  become: yes
  template: src=default_cloudera-scm-server.j2 dest=/etc/default/cloudera-scm-server
  tags: cdh-scm-base

- name: Add MySQL JDBC connector
  become: yes
  copy: src=mysql-connector-java-5.1.40-bin.jar dest=/usr/share/java/mysql-connector-java.jar
  when: cloudera_external_database is defined

- name: Update Cloudera Manager DB configuration
  become: yes
  template: src=db.properties.j2 dest=/etc/cloudera-scm-server/db.properties
  when: cloudera_external_database is defined
  tags: cdh-scm-manager-config

- name: Install Embedded Cloudera Mananager Database
  become: yes
  yum: name=cloudera-manager-server-db-2 state=present disable_gpg_check=yes
  when: cloudera_external_database is not defined

- name: Start Embedded Cloudera Manager Database
  become: yes
  service: name=cloudera-scm-server-db state=started
  when: cloudera_external_database is not defined

- name: Pause 30'
  pause: seconds=30

- name: Start Cloudera Manager
  become: yes
  service: name=cloudera-scm-server state=restarted
  tags: cdh-scm-manager-config

- name: Check Cloudera Manager port
  wait_for: port=7180 delay=15 timeout=120
  tags: cdh-scm-manager-config

