---

#- name: Get VMs info from OpenStack
#  os_server_facts:
#    server: nginx*
#
#- name: List servers
#  debug: var=openstack_servers
#
#- name: Create a VM1 on OpenStack
#  os_server:
#       state: absent
#       auth:
#         auth_url: https://horizon-demo.carrefour.io:5000/v2.0
#         username: phenix
#         password: Phenix!
#         project_name: analytic_demo_project
#       name: vm1
#       image: 289bbfac-71fe-49ef-af66-c71f9b730881
#       key_name: ds
#       timeout: 200
#       flavor: 2
#       nics:
#         - net-name: infranet
#
#- name: Create a VM2 on OpenStack
#  os_server:
#       state: absent
#       auth:
#         auth_url: https://horizon-demo.carrefour.io:5000/v2.0
#         username: phenix
#         password: Phenix!
#         project_name: analytic_demo_project
#       name: vm2
#       image: 289bbfac-71fe-49ef-af66-c71f9b730881
#       key_name: ds
#       timeout: 200
#       flavor: 2
#       nics:
#         - net-name: infranet
#           v4-fixed-ip: 172.16.100.133

- name: Add port
  os_port:
    name: port-vm3
    network: infranet
    fixed_ips:
      - ip_address: 172.16.100.138

- name: Create VM3
  os_server:
    name: vm3
    image: 289bbfac-71fe-49ef-af66-c71f9b730881
    key_name: ds
    timeout: 200
    flavor: 2
    auto_ip: no
    nics:
      - port-name: port-vm3
    state: present

- name: Create VM3_volume
  os_volume:
    display_name: vm3_vdb
    size: 10
    state: present
    volume_type:

- name: Attach volume to VM3
  os_server_volume:
    server: vm3
    volume: vm3_vdb
    device: /dev/vdb
    state: present
