---
# Install MariaDB on CentOS

- name: Add MariaDB repository
  become: yes
  template: src=mariadb.repo.j2 dest=/etc/yum.repos.d/mariadb.repo

- name: Install MariaDB and tools
  become: yes
  yum: name={{ item }} state=present
  with_items:
  - MariaDB-server
  - MySQL-python
  run_once: true

- name: Start server to generate mysql schema
  become: yes
  service: name=mysql state=started
  run_once: true

- name: standby during restart service
  wait_for: port={{ mariadb_port }} delay=5 timeout=21
  run_once: true

- name: Change root user password on first run
  mysql_user: login_user=root
              login_password=''
              name=root
              password={{ password_root }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - "%"
    - "127.0.0.1"
    - "::1"
    - "{{ ansible_hostname }}"
    - "localhost"
  ignore_errors: yes
  run_once: true

- name: Delete anonymous user
  mysql_user: login_user=root
              login_password=''
              name=''
              host={{ item }}
              state='absent'
  with_items:
    - "127.0.0.1"
    - "localhost"
    - "%"
    - "{{ ansible_hostname }}"
  ignore_errors: yes
  run_once: true

- name: Delete test database
  mysql_db: login_user=root
            login_password={{ password_root }}
            name=test
            state='absent'
  ignore_errors: yes
  run_once: true
  tags: mariadb-test

- name: Setup my cnf for root
  become: yes
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  run_once: true

- name: mysql_items
  debug: var=mysql_items

- name: Create databases
  mysql_db: login_user=root
            login_password={{ password_root }}
            name={{ item.database }}
            state=present
  with_items: "{{ mysql_items }}"
  when: mysql_items is defined
  ignore_errors: yes
  run_once: true
  tags: mariadb-items

- name: Create databases and users
  mysql_user: login_user=root
              login_password={{ password_root }}
              name={{item.user}}
              password={{ item.password }}
              priv={{ item.database }}.*:ALL
              host={{ item.host }}
  with_items: "{{ mysql_items }}"
  when: mysql_items is defined
  ignore_errors: yes
  run_once: true
  tags: mariadb-items

