---
# Install MariaDB on CentOS / RHEL

- name: Add MariaDB repository
  become: yes
  template: src=mariadb.repo.j2 dest=/etc/yum.repos.d/mariadb.repo

- name: Install MariaDB and tools
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - MariaDB-server
    - MySQL-python
  run_once: true

