---

- name: Change Swappiness to 10
  become: yes
  shell: "sysctl vm.swappiness=10"
  tags: swappiness

- name: Make Swappiness=10 permanently
  become: yes
  lineinfile:
    dest: "/etc/sysctl.conf"
    state: "present"
    line: "vm.swappiness=10"
  tags: swappiness

- name: Disable transparent hugepage 1/2
  become: yes
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
  tags: huge-page

- name: Disable transparent hugepage 2/2
  become: yes
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/defrag"
  tags: huge-page
