---
# This role supposes that there is a new disk volume at /dev/vdb.
# This role will format the disk and mount it on /dfs

- name: Check /dev/vdb
  stat: path=/dev/vdb
  register: vdb_stat
  tags: test

- name: Debug /dev/vdb
  debug: msg="/dev/vdb exists"
  when: vdb_stat.stat.exists
  tags: test

- name: Format /dev/vdb
  become: yes
  shell: "mkfs.ext3 /dev/vdb"
  when: vdb_stat.stat.exists
  tags: test

- name: Create {{mounted_data_dir}}
  become: yes
  file: path={{mounted_data_dir}} state=directory
  when: vdb_stat.stat.exists
  tags: test

- name: Mount /dev/vdb
  become: yes
  shell: "mount /dev/vdb {{mounted_data_dir}}"
  when: vdb_stat.stat.exists
  tags: test

- name: Make /dev/vdb auto-mounted
  become: yes
  lineinfile:
    dest: "/etc/fstab"
    state: "present"
    line: "/dev/vdb  {{mounted_data_dir}}  ext3  defaults,nofail  0 0"
  when: vdb_stat.stat.exists
  tags: test

- name: Change Swappiness to 10
  become: yes
  shell: "sysctl vm.swappiness=10"
  tags: swappiness

- name: Make Swappiness=10 permanently
  become: yes
  lineinfile:
    dest: "/etc/sysctl.conf"
    state: "present"
    line: "vm.swappiness=10"
  tags: swappiness

- name: Disable transparent hugepage 1/2
  become: yes
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
  tags: huge-page

- name: Disable transparent hugepage 2/2
  become: yes
  shell: "echo never > /sys/kernel/mm/transparent_hugepage/defrag"
  tags: huge-page
