---
# Install Kerberos client

- name: Install Kerberos packages
  become: yes
  yum: name={{ item }} update_cache=yes
  with_items:
  - krb5-libs
  - krb5-workstation
  - krb5-auth-dialog

- name: Copy UnlimitedJCEPolicy [1]
  become: yes
  copy: src=local_policy.jar dest=/usr/java/jdk1.7.0_67-cloudera/jre/lib/security/

- name: Copy UnlimitedJCEPolicy [2]
  become: yes
  copy: src=US_export_policy.jar dest=/usr/java/jdk1.7.0_67-cloudera/jre/lib/security/

- name: Copy Kerberos configuration
  become: yes
  template: src=krb5.conf.j2 dest=/etc/krb5.conf
